// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozonmp/bss-workplace-api/internal/repo (interfaces: Repo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/ozonmp/bss-workplace-api/internal/model"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// CreateWorkplace mocks base method.
func (m *MockRepo) CreateWorkplace(arg0 context.Context, arg1 string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkplace", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkplace indicates an expected call of CreateWorkplace.
func (mr *MockRepoMockRecorder) CreateWorkplace(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkplace", reflect.TypeOf((*MockRepo)(nil).CreateWorkplace), arg0, arg1)
}

// DescribeWorkplace mocks base method.
func (m *MockRepo) DescribeWorkplace(arg0 context.Context, arg1 uint64) (*model.Workplace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeWorkplace", arg0, arg1)
	ret0, _ := ret[0].(*model.Workplace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeWorkplace indicates an expected call of DescribeWorkplace.
func (mr *MockRepoMockRecorder) DescribeWorkplace(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeWorkplace", reflect.TypeOf((*MockRepo)(nil).DescribeWorkplace), arg0, arg1)
}

// ListWorkplaces mocks base method.
func (m *MockRepo) ListWorkplaces(arg0 context.Context) ([]model.Workplace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWorkplaces", arg0)
	ret0, _ := ret[0].([]model.Workplace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWorkplaces indicates an expected call of ListWorkplaces.
func (mr *MockRepoMockRecorder) ListWorkplaces(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorkplaces", reflect.TypeOf((*MockRepo)(nil).ListWorkplaces), arg0)
}

// RemoveWorkplace mocks base method.
func (m *MockRepo) RemoveWorkplace(arg0 context.Context, arg1 uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveWorkplace", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveWorkplace indicates an expected call of RemoveWorkplace.
func (mr *MockRepoMockRecorder) RemoveWorkplace(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWorkplace", reflect.TypeOf((*MockRepo)(nil).RemoveWorkplace), arg0, arg1)
}
