// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozonmp/bss-workplace-api/internal/service (interfaces: WorkplaceService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/ozonmp/bss-workplace-api/internal/model"
)

// MockWorkplaceService is a mock of WorkplaceService interface.
type MockWorkplaceService struct {
	ctrl     *gomock.Controller
	recorder *MockWorkplaceServiceMockRecorder
}

// MockWorkplaceServiceMockRecorder is the mock recorder for MockWorkplaceService.
type MockWorkplaceServiceMockRecorder struct {
	mock *MockWorkplaceService
}

// NewMockWorkplaceService creates a new mock instance.
func NewMockWorkplaceService(ctrl *gomock.Controller) *MockWorkplaceService {
	mock := &MockWorkplaceService{ctrl: ctrl}
	mock.recorder = &MockWorkplaceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkplaceService) EXPECT() *MockWorkplaceServiceMockRecorder {
	return m.recorder
}

// CreateWorkplace mocks base method.
func (m *MockWorkplaceService) CreateWorkplace(arg0 context.Context, arg1 string, arg2 uint32) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkplace", arg0, arg1, arg2)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkplace indicates an expected call of CreateWorkplace.
func (mr *MockWorkplaceServiceMockRecorder) CreateWorkplace(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkplace", reflect.TypeOf((*MockWorkplaceService)(nil).CreateWorkplace), arg0, arg1, arg2)
}

// DescribeWorkplace mocks base method.
func (m *MockWorkplaceService) DescribeWorkplace(arg0 context.Context, arg1 uint64) (*model.Workplace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeWorkplace", arg0, arg1)
	ret0, _ := ret[0].(*model.Workplace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeWorkplace indicates an expected call of DescribeWorkplace.
func (mr *MockWorkplaceServiceMockRecorder) DescribeWorkplace(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeWorkplace", reflect.TypeOf((*MockWorkplaceService)(nil).DescribeWorkplace), arg0, arg1)
}

// ListWorkplaces mocks base method.
func (m *MockWorkplaceService) ListWorkplaces(arg0 context.Context, arg1, arg2 uint64) ([]model.Workplace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWorkplaces", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model.Workplace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWorkplaces indicates an expected call of ListWorkplaces.
func (mr *MockWorkplaceServiceMockRecorder) ListWorkplaces(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorkplaces", reflect.TypeOf((*MockWorkplaceService)(nil).ListWorkplaces), arg0, arg1, arg2)
}

// RemoveWorkplace mocks base method.
func (m *MockWorkplaceService) RemoveWorkplace(arg0 context.Context, arg1 uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveWorkplace", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveWorkplace indicates an expected call of RemoveWorkplace.
func (mr *MockWorkplaceServiceMockRecorder) RemoveWorkplace(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWorkplace", reflect.TypeOf((*MockWorkplaceService)(nil).RemoveWorkplace), arg0, arg1)
}

// UpdateWorkplace mocks base method.
func (m *MockWorkplaceService) UpdateWorkplace(arg0 context.Context, arg1 model.Workplace) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkplace", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkplace indicates an expected call of UpdateWorkplace.
func (mr *MockWorkplaceServiceMockRecorder) UpdateWorkplace(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkplace", reflect.TypeOf((*MockWorkplaceService)(nil).UpdateWorkplace), arg0, arg1)
}
