// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package bss_workplace_facade

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BssFacadeEventsApiServiceClient is the client API for BssFacadeEventsApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BssFacadeEventsApiServiceClient interface {
	// ListEventsV1 - List events
	ListEventsV1(ctx context.Context, in *ListEventsV1Request, opts ...grpc.CallOption) (*ListEventsV1Response, error)
}

type bssFacadeEventsApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBssFacadeEventsApiServiceClient(cc grpc.ClientConnInterface) BssFacadeEventsApiServiceClient {
	return &bssFacadeEventsApiServiceClient{cc}
}

func (c *bssFacadeEventsApiServiceClient) ListEventsV1(ctx context.Context, in *ListEventsV1Request, opts ...grpc.CallOption) (*ListEventsV1Response, error) {
	out := new(ListEventsV1Response)
	err := c.cc.Invoke(ctx, "/ozonmp.bss_workplace_facade.v1.BssFacadeEventsApiService/ListEventsV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BssFacadeEventsApiServiceServer is the server API for BssFacadeEventsApiService service.
// All implementations must embed UnimplementedBssFacadeEventsApiServiceServer
// for forward compatibility
type BssFacadeEventsApiServiceServer interface {
	// ListEventsV1 - List events
	ListEventsV1(context.Context, *ListEventsV1Request) (*ListEventsV1Response, error)
	mustEmbedUnimplementedBssFacadeEventsApiServiceServer()
}

// UnimplementedBssFacadeEventsApiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBssFacadeEventsApiServiceServer struct {
}

func (UnimplementedBssFacadeEventsApiServiceServer) ListEventsV1(context.Context, *ListEventsV1Request) (*ListEventsV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEventsV1 not implemented")
}
func (UnimplementedBssFacadeEventsApiServiceServer) mustEmbedUnimplementedBssFacadeEventsApiServiceServer() {
}

// UnsafeBssFacadeEventsApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BssFacadeEventsApiServiceServer will
// result in compilation errors.
type UnsafeBssFacadeEventsApiServiceServer interface {
	mustEmbedUnimplementedBssFacadeEventsApiServiceServer()
}

func RegisterBssFacadeEventsApiServiceServer(s grpc.ServiceRegistrar, srv BssFacadeEventsApiServiceServer) {
	s.RegisterService(&BssFacadeEventsApiService_ServiceDesc, srv)
}

func _BssFacadeEventsApiService_ListEventsV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BssFacadeEventsApiServiceServer).ListEventsV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonmp.bss_workplace_facade.v1.BssFacadeEventsApiService/ListEventsV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BssFacadeEventsApiServiceServer).ListEventsV1(ctx, req.(*ListEventsV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// BssFacadeEventsApiService_ServiceDesc is the grpc.ServiceDesc for BssFacadeEventsApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BssFacadeEventsApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ozonmp.bss_workplace_facade.v1.BssFacadeEventsApiService",
	HandlerType: (*BssFacadeEventsApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEventsV1",
			Handler:    _BssFacadeEventsApiService_ListEventsV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ozonmp/bss_workplace_facade/v1/bss_workplace_facade.proto",
}
