// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: ozonmp/bss_workplace_facade/v1/bss_workplace_facade.proto

/*
Package bss_workplace_facade is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package bss_workplace_facade

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

var (
	filter_BssFacadeEventsApiService_ListEventsV1_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_BssFacadeEventsApiService_ListEventsV1_0(ctx context.Context, marshaler runtime.Marshaler, client BssFacadeEventsApiServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq ListEventsV1Request
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_BssFacadeEventsApiService_ListEventsV1_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.ListEventsV1(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_BssFacadeEventsApiService_ListEventsV1_0(ctx context.Context, marshaler runtime.Marshaler, server BssFacadeEventsApiServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq ListEventsV1Request
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_BssFacadeEventsApiService_ListEventsV1_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.ListEventsV1(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterBssFacadeEventsApiServiceHandlerServer registers the http handlers for service BssFacadeEventsApiService to "mux".
// UnaryRPC     :call BssFacadeEventsApiServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterBssFacadeEventsApiServiceHandlerFromEndpoint instead.
func RegisterBssFacadeEventsApiServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server BssFacadeEventsApiServiceServer) error {

	mux.Handle("GET", pattern_BssFacadeEventsApiService_ListEventsV1_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/ozonmp.bss_workplace_facade.v1.BssFacadeEventsApiService/ListEventsV1", runtime.WithHTTPPathPattern("/v1/events"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_BssFacadeEventsApiService_ListEventsV1_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_BssFacadeEventsApiService_ListEventsV1_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterBssFacadeEventsApiServiceHandlerFromEndpoint is same as RegisterBssFacadeEventsApiServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterBssFacadeEventsApiServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterBssFacadeEventsApiServiceHandler(ctx, mux, conn)
}

// RegisterBssFacadeEventsApiServiceHandler registers the http handlers for service BssFacadeEventsApiService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterBssFacadeEventsApiServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterBssFacadeEventsApiServiceHandlerClient(ctx, mux, NewBssFacadeEventsApiServiceClient(conn))
}

// RegisterBssFacadeEventsApiServiceHandlerClient registers the http handlers for service BssFacadeEventsApiService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "BssFacadeEventsApiServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "BssFacadeEventsApiServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "BssFacadeEventsApiServiceClient" to call the correct interceptors.
func RegisterBssFacadeEventsApiServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client BssFacadeEventsApiServiceClient) error {

	mux.Handle("GET", pattern_BssFacadeEventsApiService_ListEventsV1_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/ozonmp.bss_workplace_facade.v1.BssFacadeEventsApiService/ListEventsV1", runtime.WithHTTPPathPattern("/v1/events"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_BssFacadeEventsApiService_ListEventsV1_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_BssFacadeEventsApiService_ListEventsV1_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_BssFacadeEventsApiService_ListEventsV1_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"v1", "events"}, ""))
)

var (
	forward_BssFacadeEventsApiService_ListEventsV1_0 = runtime.ForwardResponseMessage
)
