// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ozonmp/bss_workplace_facade/v1/bss_workplace_facade.proto

package bss_workplace_facade

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on Workplace with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Workplace) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Size

	if v, ok := interface{}(m.GetCreated()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WorkplaceValidationError{
				field:  "Created",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// WorkplaceValidationError is the validation error returned by
// Workplace.Validate if the designated constraints aren't met.
type WorkplaceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WorkplaceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WorkplaceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WorkplaceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WorkplaceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WorkplaceValidationError) ErrorName() string { return "WorkplaceValidationError" }

// Error satisfies the builtin error interface
func (e WorkplaceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWorkplace.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WorkplaceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WorkplaceValidationError{}

// Validate checks the field values on WorkplaceEvent with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *WorkplaceEvent) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for EventType

	// no validation rules for EventStatus

	if v, ok := interface{}(m.GetWorkplace()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WorkplaceEventValidationError{
				field:  "Workplace",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// WorkplaceEventValidationError is the validation error returned by
// WorkplaceEvent.Validate if the designated constraints aren't met.
type WorkplaceEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WorkplaceEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WorkplaceEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WorkplaceEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WorkplaceEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WorkplaceEventValidationError) ErrorName() string { return "WorkplaceEventValidationError" }

// Error satisfies the builtin error interface
func (e WorkplaceEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWorkplaceEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WorkplaceEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WorkplaceEventValidationError{}

// Validate checks the field values on ListEventsV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListEventsV1Request) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Offset

	if m.GetLimit() <= 0 {
		return ListEventsV1RequestValidationError{
			field:  "Limit",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// ListEventsV1RequestValidationError is the validation error returned by
// ListEventsV1Request.Validate if the designated constraints aren't met.
type ListEventsV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListEventsV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListEventsV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListEventsV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListEventsV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListEventsV1RequestValidationError) ErrorName() string {
	return "ListEventsV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListEventsV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListEventsV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListEventsV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListEventsV1RequestValidationError{}

// Validate checks the field values on ListEventsV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListEventsV1Response) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListEventsV1ResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	return nil
}

// ListEventsV1ResponseValidationError is the validation error returned by
// ListEventsV1Response.Validate if the designated constraints aren't met.
type ListEventsV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListEventsV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListEventsV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListEventsV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListEventsV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListEventsV1ResponseValidationError) ErrorName() string {
	return "ListEventsV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListEventsV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListEventsV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListEventsV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListEventsV1ResponseValidationError{}
