# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: ozonmp/bss_workplace_facade/v1/bss_workplace_facade.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import validate.validate_pb2
import google.api.annotations_pb2
import google.protobuf.timestamp_pb2
import ozonmp.bss_workplace_facade.v1.bss_workplace_facade_pb2


class BssFacadeEventsApiServiceBase(abc.ABC):

    @abc.abstractmethod
    async def ListEventsV1(self, stream: 'grpclib.server.Stream[ozonmp.bss_workplace_facade.v1.bss_workplace_facade_pb2.ListEventsV1Request, ozonmp.bss_workplace_facade.v1.bss_workplace_facade_pb2.ListEventsV1Response]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/ozonmp.bss_workplace_facade.v1.BssFacadeEventsApiService/ListEventsV1': grpclib.const.Handler(
                self.ListEventsV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                ozonmp.bss_workplace_facade.v1.bss_workplace_facade_pb2.ListEventsV1Request,
                ozonmp.bss_workplace_facade.v1.bss_workplace_facade_pb2.ListEventsV1Response,
            ),
        }


class BssFacadeEventsApiServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.ListEventsV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.bss_workplace_facade.v1.BssFacadeEventsApiService/ListEventsV1',
            ozonmp.bss_workplace_facade.v1.bss_workplace_facade_pb2.ListEventsV1Request,
            ozonmp.bss_workplace_facade.v1.bss_workplace_facade_pb2.ListEventsV1Response,
        )
