# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ozonmp/bss_workplace_facade/v1/bss_workplace_facade.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ozonmp/bss_workplace_facade/v1/bss_workplace_facade.proto',
  package='ozonmp.bss_workplace_facade.v1',
  syntax='proto3',
  serialized_options=_b('ZTgithub.com/ozonmp/bss-workplace-facade/pkg/bss-workplace-facade;bss_workplace_facade'),
  serialized_pb=_b('\n9ozonmp/bss_workplace_facade/v1/bss_workplace_facade.proto\x12\x1eozonmp.bss_workplace_facade.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"y\n\tWorkplace\x12\x0e\n\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n\x04size\x18\x03 \x01(\rR\x04size\x12\x34\n\x07\x63reated\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x07\x63reated\"\xab\x01\n\x0eWorkplaceEvent\x12\x0e\n\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n\nevent_type\x18\x02 \x01(\rR\teventType\x12!\n\x0c\x65vent_status\x18\x03 \x01(\rR\x0b\x65ventStatus\x12G\n\tworkplace\x18\x04 \x01(\x0b\x32).ozonmp.bss_workplace_facade.v1.WorkplaceR\tworkplace\"L\n\x13ListEventsV1Request\x12\x16\n\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x1d\n\x05limit\x18\x02 \x01(\x04\x42\x07\xfa\x42\x04\x32\x02 \x00R\x05limit\"r\n\x14ListEventsV1Response\x12\x44\n\x05items\x18\x01 \x03(\x0b\x32..ozonmp.bss_workplace_facade.v1.WorkplaceEventR\x05items\x12\x14\n\x05total\x18\x02 \x01(\x04R\x05total2\xab\x01\n\x19\x42ssFacadeEventsApiService\x12\x8d\x01\n\x0cListEventsV1\x12\x33.ozonmp.bss_workplace_facade.v1.ListEventsV1Request\x1a\x34.ozonmp.bss_workplace_facade.v1.ListEventsV1Response\"\x12\x82\xd3\xe4\x93\x02\x0c\x12\n/v1/eventsBVZTgithub.com/ozonmp/bss-workplace-facade/pkg/bss-workplace-facade;bss_workplace_facadeb\x06proto3')
  ,
  dependencies=[validate_dot_validate__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_WORKPLACE = _descriptor.Descriptor(
  name='Workplace',
  full_name='ozonmp.bss_workplace_facade.v1.Workplace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ozonmp.bss_workplace_facade.v1.Workplace.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='id', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ozonmp.bss_workplace_facade.v1.Workplace.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='name', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='ozonmp.bss_workplace_facade.v1.Workplace.size', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='size', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created', full_name='ozonmp.bss_workplace_facade.v1.Workplace.created', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='created', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=302,
)


_WORKPLACEEVENT = _descriptor.Descriptor(
  name='WorkplaceEvent',
  full_name='ozonmp.bss_workplace_facade.v1.WorkplaceEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ozonmp.bss_workplace_facade.v1.WorkplaceEvent.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='id', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_type', full_name='ozonmp.bss_workplace_facade.v1.WorkplaceEvent.event_type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='eventType', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_status', full_name='ozonmp.bss_workplace_facade.v1.WorkplaceEvent.event_status', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='eventStatus', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workplace', full_name='ozonmp.bss_workplace_facade.v1.WorkplaceEvent.workplace', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='workplace', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=476,
)


_LISTEVENTSV1REQUEST = _descriptor.Descriptor(
  name='ListEventsV1Request',
  full_name='ozonmp.bss_workplace_facade.v1.ListEventsV1Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='ozonmp.bss_workplace_facade.v1.ListEventsV1Request.offset', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='offset', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit', full_name='ozonmp.bss_workplace_facade.v1.ListEventsV1Request.limit', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\372B\0042\002 \000'), json_name='limit', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=478,
  serialized_end=554,
)


_LISTEVENTSV1RESPONSE = _descriptor.Descriptor(
  name='ListEventsV1Response',
  full_name='ozonmp.bss_workplace_facade.v1.ListEventsV1Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='ozonmp.bss_workplace_facade.v1.ListEventsV1Response.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='items', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total', full_name='ozonmp.bss_workplace_facade.v1.ListEventsV1Response.total', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='total', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=556,
  serialized_end=670,
)

_WORKPLACE.fields_by_name['created'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_WORKPLACEEVENT.fields_by_name['workplace'].message_type = _WORKPLACE
_LISTEVENTSV1RESPONSE.fields_by_name['items'].message_type = _WORKPLACEEVENT
DESCRIPTOR.message_types_by_name['Workplace'] = _WORKPLACE
DESCRIPTOR.message_types_by_name['WorkplaceEvent'] = _WORKPLACEEVENT
DESCRIPTOR.message_types_by_name['ListEventsV1Request'] = _LISTEVENTSV1REQUEST
DESCRIPTOR.message_types_by_name['ListEventsV1Response'] = _LISTEVENTSV1RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Workplace = _reflection.GeneratedProtocolMessageType('Workplace', (_message.Message,), dict(
  DESCRIPTOR = _WORKPLACE,
  __module__ = 'ozonmp.bss_workplace_facade.v1.bss_workplace_facade_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.bss_workplace_facade.v1.Workplace)
  ))
_sym_db.RegisterMessage(Workplace)

WorkplaceEvent = _reflection.GeneratedProtocolMessageType('WorkplaceEvent', (_message.Message,), dict(
  DESCRIPTOR = _WORKPLACEEVENT,
  __module__ = 'ozonmp.bss_workplace_facade.v1.bss_workplace_facade_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.bss_workplace_facade.v1.WorkplaceEvent)
  ))
_sym_db.RegisterMessage(WorkplaceEvent)

ListEventsV1Request = _reflection.GeneratedProtocolMessageType('ListEventsV1Request', (_message.Message,), dict(
  DESCRIPTOR = _LISTEVENTSV1REQUEST,
  __module__ = 'ozonmp.bss_workplace_facade.v1.bss_workplace_facade_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.bss_workplace_facade.v1.ListEventsV1Request)
  ))
_sym_db.RegisterMessage(ListEventsV1Request)

ListEventsV1Response = _reflection.GeneratedProtocolMessageType('ListEventsV1Response', (_message.Message,), dict(
  DESCRIPTOR = _LISTEVENTSV1RESPONSE,
  __module__ = 'ozonmp.bss_workplace_facade.v1.bss_workplace_facade_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.bss_workplace_facade.v1.ListEventsV1Response)
  ))
_sym_db.RegisterMessage(ListEventsV1Response)


DESCRIPTOR._options = None
_LISTEVENTSV1REQUEST.fields_by_name['limit']._options = None

_BSSFACADEEVENTSAPISERVICE = _descriptor.ServiceDescriptor(
  name='BssFacadeEventsApiService',
  full_name='ozonmp.bss_workplace_facade.v1.BssFacadeEventsApiService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=673,
  serialized_end=844,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListEventsV1',
    full_name='ozonmp.bss_workplace_facade.v1.BssFacadeEventsApiService.ListEventsV1',
    index=0,
    containing_service=None,
    input_type=_LISTEVENTSV1REQUEST,
    output_type=_LISTEVENTSV1RESPONSE,
    serialized_options=_b('\202\323\344\223\002\014\022\n/v1/events'),
  ),
])
_sym_db.RegisterServiceDescriptor(_BSSFACADEEVENTSAPISERVICE)

DESCRIPTOR.services_by_name['BssFacadeEventsApiService'] = _BSSFACADEEVENTSAPISERVICE

# @@protoc_insertion_point(module_scope)
